PKGDIR	?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET	= kb_client

# list your .c or .cc files here
SRC_CC	= main.cc

# list requirements of your program here
REQUIRES_LIBS = libstdc++ libpthread

include $(L4DIR)/mk/prog.mk