PKGDIR	?= ../..
L4DIR		?= $(PKGDIR)/../..

TARGET	= fb_kb_drv

# list your .c or .cc files here
SRC_CC	= main.cc

# list requirements of your program here
REQUIRES_LIBS = l4re_c-util libio libstdc++ libpthread

include $(L4DIR)/mk/prog.mk